version: "3.8"
services:
  database:
    image: mysql:5.7.44
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=example
      - TZ=Asia/Bangkok
    volumes:
      - ./tmp/mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=database
    ports:
      - 8302:80

  admin:
    container_name: test.eveye.com
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - 1337:1337
    volumes:
      - ./admin:/app
      - /app/node_modules
      - /app/.tmp
      - /app/build
    depends_on:
      - database